import os
import warnings
import logging

warnings.filterwarnings("ignore")

# Set up logging so we can see the sub-queries generated by the MultiQueryRetriever
logging.basicConfig()
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
from langchain_ollama.llms import OllamaLLM
from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
import shutil
from langchain_core.prompts import ChatPromptTemplate

def main():
    print("0. Cleaning up old database...")
    shutil.rmtree("./chroma_db_advanced", ignore_errors=True)

    print("1. Initializing models from local Ollama...")
    llm = OllamaLLM(model="llama3.2")
    embeddings = OllamaEmbeddings(model="nomic-embed-text")
    
    print("2. Loading documents from 'data/' directory...")
    loader = DirectoryLoader('./data', glob="**/*.txt", loader_cls=TextLoader)
    docs = loader.load()
    
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=50)
    splits = text_splitter.split_documents(docs)
    
    print("3. Setting up local ChromaDB vector store...")
    # Use a different persist directory so it doesn't mix with basic_rag.py data
    vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings, persist_directory="./chroma_db_advanced")
    
    # Base retriever
    base_retriever = vectorstore.as_retriever(search_kwargs={"k": 2})
    
    print("4. Creating the ADVANCED Multi-Query Retriever...")
    # This is the magic! It will use the LLM to rewrite the query into multiple sub-queries
    # and fetch documents for ALL of them.
    advanced_retriever = MultiQueryRetriever.from_llm(
        retriever=base_retriever, 
        llm=llm
    )
    
    print("5. Creating Query Engine...")
    system_prompt = (
        "You are a highly intelligent assistant for question-answering tasks. "
        "Use the following pieces of retrieved context to answer the question. "
        "Pay close attention to names, titles, and mathematical changes over time. "
        "Calculate final sums if necessary. "
        "\n\n"
        "Context:\n{context}"
    )
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])
    
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    rag_chain = create_retrieval_chain(advanced_retriever, question_answer_chain)

    print("\n--- Indexing Complete. Type 'exit' to quit. ---\n")
    
    while True:
        question = input("\nAsk a question: ")
        if question.lower() in ['exit', 'quit']:
            break
            
        print("Thinking (Generating sub-queries and retrieving chunks...). Watch the logs below!\n")
        response = rag_chain.invoke({"input": question})
        
        print("\n=== FINAL ANSWER ===")
        print(response["answer"])
        print("====================")
        
        print("\nSource Chunks retrieved to answer this:")
        for i, doc in enumerate(response["context"]):
            print(f"\n[Source {i+1}] {doc.page_content.strip()[:200]}...")

if __name__ == "__main__":
    main()
