import os
import warnings
import logging

warnings.filterwarnings("ignore")

# Set up logging so we can see the sub-queries generated by the MultiQueryRetriever
logging.basicConfig()
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

from langchain_chroma import Chroma
from langchain_ollama import OllamaEmbeddings
from langchain_ollama.llms import OllamaLLM
from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate
from langchain.prompts import PromptTemplate

DB_DIR = "./chroma_db_mahabharata"

def run_query_loop():
    print("1. Initializing models from local Ollama...")
    llm = OllamaLLM(model="llama3.2")
    embeddings = OllamaEmbeddings(model="nomic-embed-text")
    
    print(f"2. Connecting to existing database at {DB_DIR}...")
    # We DO NOT from_documents here. We just load the existing directory.
    vectorstore = Chroma(persist_directory=DB_DIR, embedding_function=embeddings)
    base_retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
    
    print("3. Creating the ADVANCED Multi-Query Retriever...")
    
    QUERY_PROMPT = PromptTemplate(
        input_variables=["question"],
        template="""You are an AI language model assistant. Your task is to generate 3 different versions of the given user question to retrieve relevant documents from a vector database. 
By generating multiple perspectives on the user question, your goal is to help the user overcome some of the limitations of distance-based similarity search. 

Please make sure to use the exact names provided by the user in your generated questions, even if they are spelled unusually (like Arjunos or Krishnos).

Provide these alternative questions separated by newlines.
Original question: {question}"""
    )
    
    advanced_retriever = MultiQueryRetriever.from_llm(
        retriever=base_retriever, 
        llm=llm,
        prompt=QUERY_PROMPT
    )
    
    print("4. Creating Query Engine...")
    system_prompt = (
        "You are a highly intelligent literature assistant. "
        "Use the following pieces of retrieved context to answer the question about the story. "
        "Use character names exactly as they are presented in the text (e.g., Arjunos, Krishnos). "
        "If the answer is not contained in the text, say you don't know based on the provided context."
        "\n\n"
        "Context:\n{context}"
    )
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", "{input}"),
    ])
    
    question_answer_chain = create_stuff_documents_chain(llm, prompt)
    rag_chain = create_retrieval_chain(advanced_retriever, question_answer_chain)

    print("\n--- System Ready. Type 'exit' to quit. ---\n")
    
    while True:
        question = input("\nAsk a question about the story: ")
        if question.lower() in ['exit', 'quit']:
            break
            
        print("\nThinking (Generating sub-queries and retrieving chunks...). Watch the logs below!\n")
        response = rag_chain.invoke({"input": question})
        
        print("\n=== FINAL ANSWER ===")
        print(response["answer"])
        print("====================")
        
        print("\nSource Chunks retrieved to answer this:")
        for i, doc in enumerate(response["context"]):
            print(f"\n[Source {i+1}] {doc.page_content.strip()[:200]}...")

if __name__ == "__main__":
    if not os.path.exists(DB_DIR):
        print(f"Error: Database {DB_DIR} not found. Please run build_index.py first!")
    else:
        run_query_loop()
